spring:
  application:
    name: spring-openai-demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arun
    username: root
    password: Arun@123

#  ai:
#    ollama:
#      base-url: http://localhost:11434/
#      chat:
#        model: llama3.2:1b


  ai:
    openai:
     api-key: ${OPEN_API_KEY}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: ALWAYS

    vectorstore:
     qdrant:
       initialize-schema: true
       host: localhost
       port: 6334
       collection-name: IAFRecruitmentPolicy

     docker:
        compose:
          stop:
            command: DOWN

#     chat:
#       options:
#         model: "gpt-4o"
#         temperature: 0.1
#         max-tokens: 1000


logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG


server:
  port: 8081

